### PR TITLE
Export Script

### PR DESCRIPTION
**Pull request by jasondegraw**
@CraigCasey @rpg777 The export script now does a pretty good job of getting the minimal subset to support dxgridmaker. There are still some problems with using the subset as a subproject, but for now that can be worked around. To get a subset that is standalone:

```
python export.py
```

And to get one that will work as a subdirectory of Radiance:

```
python export.py --boost-prefix src/stadic/
```

We can fix that for real later. The git SHA stuff is pretty ugly, and may require Python3 to work well. The only remaining question is what to do about the docs. Any thoughts on that?

### CODE REVIEW

**Comment by rpg777** [comment]
I was gonna ask about the documentation. Standard protocol with Radiance is there is a groff manpage (written in standard manpage style) for every executable. Typical behavior of Radiance executables is there is a simple usage help line that gets printed either when called with no input, or with '-h'; dxgridmaker has extensive help built into the exe, which could be easily lifted out and converted to a manpage and ideally replaced with either a "no input file provided" or simplified usage message. We should talk to Greg about including this in the source though. If STADIC isn't gonna be in make, one could argue that STADIC docs should live in the STADIC subdirectory and only get dealt with in the CMake. I do like having this stuff mimic the behavior or the main Radiance project, though. We should supply a blurb for the release notes.

**Comment by RMistrick** [comment]
Our plan was to include a manpage for each STADIC executeable program.

Rick

**Comment by jasondegraw** [comment]
@rpg777 There is man page here:

https://github.com/Architectural-Lighting-Simulation/STADIC/blob/develop/doc/dxgridmaker.1

but I am not sure that it is up to date. We never had much luck integrating it with the build because both @CraigCasey and I are mainly on Windows. I'd like to provide both the man page and the in-executable help.

**Comment by rpg777** [comment]
Oh. Yeah. Windows. Good point, sir. OK well I'll make sure the CMake package target picks up the dxgridmaker.1 and tosses it in with the rest of the Radiance manpages (which it places in [instdir]/doc on Mac/Linux), and if you leave all that good info on the cli help, the Windows users will be covered. Someday we'll have a step that auto-converts them all to pdf each time a new package is rolled out, but that day is not today.

**Comment by rpg777** [comment]
@CraigCasey do you have any test cases for dxgridmaker? Jason's got this exporting nicely as a subset,  and it's building within the Radiance source with CMake on Mac. I want to test its operation now before testing on other platforms and ultimately pinging Greg about folding this in.

**Comment by jasondegraw** [comment]
I'm going to go ahead and merge this, since it has some changes that are probably needed.

**Comment by rpg777** [comment]
Thanks @jasondegraw. So, ah, where is this thing at, WRT dxgridmaker?? AFAIK, there's still a bug with coincident boundaries getting duplicate points. dxgridmaker would be a very useful addition to Radiance proper...

**Pull request merged**
